# Generated by Django 2.0.5 on 2018-07-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginmodel',
            name='password',
        ),
    ]
