# Generated by Django 2.0.5 on 2018-11-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_fooditem_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_image',
            field=models.ImageField(blank=True, upload_to='D:\\Code\\MPro\\smart_res1\\smart_res\\smart_res\\photo_path'),
        ),
    ]
