# Generated by Django 2.1 on 2018-11-23 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_foodclass_fooditem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginmodel',
            name='Table_number',
        ),
    ]
